import React from "react";

const terms = [
  {
    title: "1. WURKZI’S ROLE",
    paragraphs: [
      "Wurkzi is a technology platform designed to connect individuals and businesses seeking help with local individuals, including eligible teen service providers, who wish to perform permitted services.",
      "Services may include lawn care, car detailing, cleaning, basic outdoor work, babysitting where permitted, and other lawful, non-hazardous, age-appropriate tasks approved for use on the Platform.",
      "Wurkzi is a marketplace and facilitator. Except where applicable law provides otherwise, Wurkzi does not perform the services posted on the Platform and does not control the manner or means by which users perform services.",
      "Nothing in these Terms is intended to waive, avoid, or override any employment classification, youth-employment protection, minimum wage requirement, tax obligation, or other right or obligation imposed by applicable law.",
    ],
  },
  {
    title: "2. ELIGIBILITY",
    paragraphs: ["Users must provide truthful and accurate information when creating and maintaining an account.", "Clients must be at least 18 years old and legally capable of entering into a binding agreement.", "Teen workers must:"],
    bullets: ["Be at least 15 years old;", "Have the consent of a parent or legal guardian if under 18;", "Comply with applicable youth-employment and work-permit requirements;", "Only perform services legally permitted for a person of their age; and", "Meet any additional eligibility requirements established by Wurkzi."],
    closing: "Wurkzi may request reasonable information or documentation to verify a user’s age, identity, eligibility, or parental/guardian authorization. Wurkzi may deny, restrict, suspend, or terminate access when eligibility requirements are not satisfied.",
  },
  {
    title: "3. PARENT OR LEGAL GUARDIAN CONSENT",
    paragraphs: ["A user under 18 may be required to obtain verified authorization from a parent or legal guardian before using worker features.", "By authorizing a minor’s account, the parent or legal guardian acknowledges and agrees that:"],
    bullets: ["They consent to the minor using Wurkzi;", "They understand that the minor may interact with clients through the Platform;", "They will reasonably monitor the minor’s use of Wurkzi;", "They will help ensure the minor only accepts lawful and age-appropriate work;", "They will review job details with the minor when appropriate;", "They understand that performing local services involves certain inherent risks; and", "They will assist the minor in complying with applicable youth-employment requirements."],
    closing: "Nothing in this section waives rights or protections that cannot legally be waived.",
  },
  {
    title: "4. YOUTH EMPLOYMENT AND WORK PERMITS",
    paragraphs: ["Users are responsible for complying with applicable federal, state, and local laws governing the employment or engagement of minors.", "Depending on the circumstances, these requirements may include:"],
    bullets: ["Work permits or registrations;", "Restrictions on working hours;", "School-day restrictions;", "Required adult supervision;", "Minimum wage requirements;", "Restrictions on hazardous occupations;", "Restrictions based on the worker’s age; and", "Recordkeeping or other legal requirements."],
    closing: "Clients may not use Wurkzi to request that a minor perform work prohibited by law. Parents and guardians should review proposed work before allowing a minor to perform it. Wurkzi may prohibit a service even when that service may otherwise be lawful.",
  },
  {
    title: "5. PROHIBITED AND HAZARDOUS SERVICES",
    paragraphs: ["Minor workers may not use Wurkzi to perform tasks that Wurkzi determines are unsafe, inappropriate, or prohibited by applicable law.", "Prohibited work may include, depending on the worker’s age and applicable law:"],
    bullets: ["Operating prohibited power-driven machinery or equipment;", "Roofing;", "Work at dangerous heights;", "Operating motor vehicles as part of a job where prohibited;", "Using hazardous chemicals or substances;", "Demolition;", "Excavation or trenching;", "Handling explosives or dangerous materials;", "Operating heavy machinery;", "Certain construction activities;", "Work involving illegal substances or activities;", "Tasks involving weapons;", "Work that is sexual or exploitative in nature; or", "Any other service prohibited by federal, state, or local law."],
    closing: "Clients may not attempt to disguise prohibited work by posting it under another category. Wurkzi may remove any job that it determines presents an unreasonable safety or legal risk.",
  },
  { title: "6. WORKER RELATIONSHIPS", paragraphs: ["Wurkzi provides technology that allows users to discover and arrange services.", "Except to the extent applicable law determines otherwise, Wurkzi does not intend to create an employer-employee relationship between Wurkzi and workers solely through use of the Platform.", "Wurkzi generally does not control the specific manner or means by which a service is performed.", "However, Wurkzi may establish marketplace rules, safety requirements, prohibited-service policies, eligibility standards, and community guidelines.", "Nothing in these Terms determines a user’s legal employment classification where applicable law requires a different classification."] },
  { title: "7. CLIENT RESPONSIBILITIES", paragraphs: ["Clients posting jobs through Wurkzi agree to:"], bullets: ["Accurately describe the requested work;", "Disclose material risks or conditions associated with the job;", "Provide a reasonably safe working environment;", "Request only lawful and age-appropriate services;", "Not pressure a worker to perform work outside the agreed scope;", "Not request prohibited or hazardous work;", "Treat workers respectfully;", "Provide reasonable access to equipment or materials when the job requires the client to supply them;", "Comply with applicable youth-employment requirements; and", "Pay all amounts properly due through the Platform."], closing: "Clients must not ask minor workers to conceal work from their parents, guardians, Wurkzi, schools, or government authorities." },
  { title: "8. WORKER RESPONSIBILITIES", paragraphs: ["Workers agree to:"], bullets: ["Provide accurate information;", "Only accept jobs they are legally permitted and reasonably capable of performing;", "Arrive within the agreed time when reasonably possible;", "Communicate promptly if they cannot complete a job;", "Perform agreed services in good faith;", "Treat clients and their property respectfully;", "Follow reasonable safety practices;", "Refuse work they reasonably believe is dangerous or illegal;", "Follow applicable laws and Wurkzi policies; and", "Report serious safety concerns to Wurkzi."], closing: "Workers should not enter private areas of a client’s property unless reasonably necessary for the agreed service and authorized by the client." },
  { title: "9. SAFETY", paragraphs: ["Users are responsible for exercising reasonable judgment when interacting with others through Wurkzi.", "Workers, particularly minors, are encouraged to inform a parent or guardian of the job location, client, scheduled time, and expected duration.", "Users should immediately leave a situation they reasonably believe presents an imminent threat to their safety and contact emergency services when appropriate.", "Wurkzi may provide safety features, guidance, reporting systems, verification tools, or other protections. Such features do not guarantee that a user or job is safe."] },
  { title: "10. USER CONDUCT AND ZERO-TOLERANCE POLICY", paragraphs: ["Wurkzi maintains a zero-tolerance policy toward serious abusive, exploitative, illegal, or objectionable conduct.", "Users may not:"], bullets: ["Harass, threaten, bully, stalk, or intimidate another user;", "Post pornographic or sexually exploitative content;", "Engage in sexual conduct involving minors;", "Post hate speech;", "Encourage or threaten violence;", "Post content intended primarily to disgust, shock, or seriously offend;", "Engage in discrimination prohibited by applicable law;", "Attempt to exploit or manipulate minors;", "Commit fraud or theft;", "Impersonate another person;", "Use Wurkzi for illegal activity; or", "Attempt to evade an account suspension or termination."], closing: "Users may report content, job posts, messages, or behavior using Wurkzi’s reporting features or by contacting Wurkzi support. Wurkzi may investigate reports and may remove content, cancel jobs, restrict functionality, suspend accounts, permanently terminate accounts, or take other appropriate action. Where appropriate, Wurkzi may cooperate with law enforcement or other authorities." },
  { title: "11. USER CONTENT", paragraphs: ["Users may be permitted to upload job descriptions, photographs, reviews, messages, profile information, and other content.", "Users retain ownership of their content but grant Wurkzi a non-exclusive, worldwide, royalty-free license to host, store, reproduce, display, and use that content as reasonably necessary to operate, secure, improve, and promote the Platform, subject to applicable law and Wurkzi’s Privacy Policy.", "Users may only upload content they have the legal right to use.", "Wurkzi may remove content that violates these Terms or applicable law."] },
  { title: "12. PAYMENTS AND PLATFORM FEES", paragraphs: ["Wurkzi may facilitate payments between clients and workers through Wurkzi or a third-party payment processor.", "Before completing a transaction, users will be shown applicable prices, fees, discounts, or other charges as required.", "Wurkzi may charge platform, service, processing, cancellation, or other disclosed fees.", "Users authorize Wurkzi and its payment providers to process amounts properly due in connection with transactions made through the Platform.", "Payment processing may also be subject to the terms and privacy policies of the applicable payment provider."] },
  { title: "13. CANCELLATIONS, REFUNDS AND JOB DISPUTES", paragraphs: ["Cancellation and refund eligibility may depend on when a job is canceled, whether work has begun, whether the worker arrived as agreed, and other circumstances.", "Wurkzi may review disputes and, where appropriate, issue refunds, credits, payment adjustments, or other remedies.", "Wurkzi’s assistance with a dispute does not make Wurkzi responsible for the underlying services performed by a user.", "Wurkzi may establish additional cancellation, refund, and payment-dispute policies within the Platform."] },
  { title: "14. TAXES", paragraphs: ["Users are responsible for determining and satisfying their own tax obligations arising from payments received or services performed through Wurkzi, except where Wurkzi or a payment provider is legally required to collect, withhold, report, or remit taxes.", "Wurkzi may collect taxpayer information and provide tax documents when required by law."] },
  { title: "15. BACKGROUND CHECKS AND USER VERIFICATION", paragraphs: ["Unless Wurkzi expressly states otherwise for a particular user or feature, users should not assume that another user has undergone a criminal background check.", "Identity, phone, email, age, payment, or other verification features reduce certain risks but do not guarantee a user’s identity, character, qualifications, reliability, or safety.", "Users remain responsible for exercising reasonable judgment when interacting with others."] },
  { title: "16. NO GUARANTEE OF SERVICES", paragraphs: ["Wurkzi does not guarantee:"], bullets: ["That a client will receive applications;", "That a worker will receive jobs;", "The quality of services;", "A worker’s experience or qualifications;", "That a job will be completed;", "The accuracy of every user statement;", "The conduct of users; or", "That every interaction will be free from risk."], closing: "Ratings, reviews, badges, verification indicators, and similar features are informational and are not guarantees by Wurkzi." },
  { title: "17. INSURANCE", paragraphs: ["Unless Wurkzi expressly states otherwise in writing, Wurkzi does not provide users with liability, automobile, workers’ compensation, property, health, or accident insurance solely by reason of their use of the Platform.", "Users are responsible for determining whether they need insurance coverage for their activities."] },
  { title: "18. ASSUMPTION OF RISK", paragraphs: ["Providing or receiving in-person services can involve risks, including property damage, accidents, injury, theft, disagreements, or misconduct.", "To the fullest extent permitted by applicable law, users voluntarily assume risks ordinarily associated with their interactions and transactions with other users.", "Nothing in these Terms excludes liability or rights that cannot lawfully be excluded or waived."] },
  { title: "19. LIMITATION OF LIABILITY", emphasis: true, paragraphs: ["TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, WURKZI AND ITS OWNERS, OFFICERS, DIRECTORS, EMPLOYEES, AFFILIATES, AND AGENTS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES ARISING FROM USE OF THE PLATFORM OR DEALINGS BETWEEN USERS.", "Wurkzi is not responsible for the acts or omissions of users merely because those users met through the Platform.", "These limitations do not apply where liability cannot legally be limited or excluded."] },
  { title: "20. INDEMNIFICATION", paragraphs: ["To the fullest extent permitted by law, adult users agree to indemnify and hold harmless Wurkzi and its owners, officers, directors, employees, affiliates, and agents from third-party claims, liabilities, damages, losses, and reasonable legal expenses arising from:"], bullets: ["Their material violation of these Terms;", "Their unlawful conduct;", "Their misuse of the Platform;", "Their infringement of another person’s rights; or", "Services they request or perform through Wurkzi."], closing: "Any obligations applicable to minors are subject to applicable law." },
  { title: "21. REVIEWS AND RATINGS", paragraphs: ["Users may leave truthful reviews based on their genuine experiences.", "Reviews may not contain:"], bullets: ["Knowingly false information;", "Threats;", "Harassment;", "Hate speech;", "Private personal information;", "Extortion;", "Sexually explicit material; or", "Other prohibited content."], closing: "Wurkzi may remove reviews that violate these Terms but does not guarantee that every negative or disputed review will be removed." },
  { title: "22. OFF-PLATFORM TRANSACTIONS", paragraphs: ["Wurkzi may prohibit users from using the Platform primarily to locate another user and then intentionally bypass Wurkzi’s payment or safety systems.", "Users who conduct transactions outside Wurkzi may lose protections, dispute assistance, records, or other features provided through the Platform.", "Wurkzi may suspend accounts engaged in repeated circumvention where permitted by law and disclosed by Platform policy."] },
  { title: "23. SUSPENSION AND TERMINATION", paragraphs: ["Wurkzi may restrict, suspend, or terminate an account when reasonably necessary to protect users, enforce these Terms, prevent fraud, address safety concerns, comply with law, or protect the Platform.", "Serious violations may result in immediate permanent termination.", "Users may stop using Wurkzi at any time.", "Provisions that by their nature should survive termination, including applicable liability, dispute, payment, and indemnification provisions, will survive."] },
  { title: "24. PRIVACY", paragraphs: ["Use of Wurkzi is also governed by Wurkzi’s Privacy Policy.", "Wurkzi may collect and process information such as account information, communications, job information, transaction information, device information, location-related information, and other data as described in the Privacy Policy.", "Because Wurkzi may be used by minors, Wurkzi may implement additional parental-consent, age-assurance, privacy, and safety requirements where required by law."] },
  { title: "25. INTELLECTUAL PROPERTY", paragraphs: ["The Wurkzi name, logo, software, design, graphics, interfaces, and other proprietary Platform materials are owned by Wurkzi or its licensors and are protected by applicable intellectual-property laws.", "Users may not copy, reverse engineer, distribute, sell, or exploit Wurkzi’s proprietary materials except as permitted by law or expressly authorized by Wurkzi."] },
  { title: "26. PLATFORM AVAILABILITY", paragraphs: ["Wurkzi may modify, suspend, discontinue, or restrict portions of the Platform.", "Wurkzi does not guarantee uninterrupted or error-free operation.", "Wurkzi may introduce, modify, or discontinue features as the Platform develops."] },
  { title: "27. DISPUTE RESOLUTION", paragraphs: ["Before commencing formal proceedings, users and Wurkzi agree to make a good-faith effort to resolve disputes informally.", "A user should first contact Wurkzi support and provide a reasonable opportunity for the issue to be addressed.", "To the extent permitted by applicable law, unresolved disputes may be subject to mediation and/or binding individual arbitration under procedures separately identified by Wurkzi.", "Any arbitration provision, class-action waiver, governing-law provision, or limitation involving a minor will apply only to the extent legally enforceable.", "Governing Law: State of Michigan, except where applicable federal law or another jurisdiction’s mandatory law controls.", "Because arbitration provisions can significantly affect legal rights, Wurkzi should obtain legal review before implementing a mandatory arbitration or class-action-waiver provision."] },
  { title: "28. CHANGES TO THESE TERMS", paragraphs: ["Wurkzi may update these Terms from time to time.", "When legally required, Wurkzi will provide notice of material changes.", "Continued use of the Platform after updated Terms become effective constitutes acceptance to the extent permitted by law.", "If a change requires additional consent, Wurkzi may require users, parents, or guardians to affirmatively accept the updated Terms."] },
  { title: "29. SEVERABILITY", paragraphs: ["If any provision of these Terms is determined to be invalid or unenforceable, the remaining provisions will remain effective to the fullest extent permitted by law."] },
  { title: "30. NO WAIVER", paragraphs: ["Wurkzi’s failure to enforce a provision of these Terms does not waive its right to enforce that provision in the future."] },
  { title: "31. ENTIRE AGREEMENT", paragraphs: ["These Terms, together with Wurkzi’s Privacy Policy and any additional policies or agreements expressly incorporated into these Terms, constitute the agreement between the user and Wurkzi regarding use of the Platform."] },
  { title: "32. CONTACT INFORMATION", paragraphs: ["Questions, safety concerns, reports, or legal notices regarding these Terms may be directed to:", "Wurkzi\nSupport Email: Nkizy@Wurkzi.com\nLegal Email: Nkizy@Wurkzi.com\nBusiness Address: 41646 Tarragon Dr", "For emergencies or immediate threats to personal safety, users should contact the appropriate emergency services rather than relying solely on Wurkzi’s reporting system."] },
  { title: "33. ACKNOWLEDGMENT", paragraphs: ["By creating an account or using Wurkzi, adult users acknowledge that they have read, understood, and agreed to these Terms.", "For users under 18, Wurkzi may require a parent or legal guardian to separately review and approve the minor’s participation before worker features are enabled.", "Parents and guardians acknowledge that Wurkzi is a technology platform connecting users and that in-person service arrangements may involve risks that require appropriate parental oversight and judgment."] },
];

const Terms = () => (
  <div className="min-h-screen bg-slate-950 px-4 py-12 text-slate-300 sm:px-6 lg:px-8">
    <article className="mx-auto max-w-4xl rounded-2xl border border-slate-700 bg-slate-900/50 p-8 shadow-xl backdrop-blur-md">
      <header className="border-b border-slate-700 pb-6">
        <h1 className="text-3xl font-bold text-white">Wurkzi Terms of Service</h1>
        <p className="mt-3 text-sm text-slate-400">Effective Date: August 10, 2026</p>
        <p className="text-sm text-slate-400">Last Updated: August 10, 2026</p>
      </header>

      <div className="prose prose-invert prose-lg mt-8 max-w-none">
        <p>These Terms of Service (“Terms”) govern your access to and use of the Wurkzi mobile application, website, services, and related features (collectively, the “Platform”).</p>
        <p>By creating an account, accessing the Platform, posting a job, applying for or accepting a job, providing parental or guardian consent, or otherwise using Wurkzi, you agree to these Terms.</p>
        <p>If you do not agree to these Terms, you may not use Wurkzi.</p>

        {terms.map((section) => (
          <section key={section.title} className="border-t border-slate-800 pt-7 mt-8">
            <h2 className="text-xl font-semibold text-wurkzi-400">{section.title}</h2>
            {section.paragraphs.map((paragraph, index) => (
              <p key={index} className={section.emphasis && index === 0 ? "font-semibold text-slate-100" : "text-slate-400 whitespace-pre-line"}>{paragraph}</p>
            ))}
            {section.bullets && (
              <ul className="list-disc space-y-2 pl-6 text-slate-400">
                {section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}
              </ul>
            )}
            {section.closing && <p className="text-slate-400">{section.closing}</p>}
          </section>
        ))}
      </div>
    </article>
  </div>
);

export default Terms;
